crosstool-ng: Use -lncurses, don't autodetect
Instead of -lncursesw, which might work in configure's autodetection
(because it finds it in /lib, for example) but then fail during the
actual build (because it lacks symbols needed by -lpanel).

Fixes
    p_delete.c(.text+0x26): undefined reference to `_nc_panelhook_sp'
and similar errors, observed on Slackware 14.2.